In [1]:
import numpy as np


In [2]:
arr1=np.arange(1,11)

In [3]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr2=np.random.rand(3,4)
arr2

array([[0.22833928, 0.93422705, 0.49109069, 0.76813237],
       [0.8109049 , 0.4312444 , 0.26033726, 0.81156139],
       [0.6020143 , 0.7266623 , 0.20759139, 0.69324698]])

In [5]:
arr3=np.zeros((2,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Q.N.2


In [16]:
arr_1=np.array([1,2,3])
arr_1


array([1, 2, 3])

In [18]:
arr_2=np.array([4,5,6])
arr_2


array([4, 5, 6])

In [19]:
add=arr_1+arr_2

In [20]:
add

array([5, 7, 9])

In [21]:
sub=arr_1-arr_2
sub

array([-3, -3, -3])

In [22]:
mul=arr_1*arr_2
mul

array([ 4, 10, 18])

In [23]:
div=arr_1/arr_2
div

array([0.25, 0.4 , 0.5 ])

In [24]:
mean=np.mean(arr_1)
mean

2.0

In [25]:
median=np.median(arr_1)
median

2.0

In [26]:
sd=np.std(arr_1)
sd

0.816496580927726

In [27]:
array_reshaped=np.arange(12).reshape(3,4)

In [28]:
array_reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Q.N.3


In [30]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
first_row=arr_2d[0,:]
first_row

array([1, 2, 3])

In [33]:
last_column=arr_2d[:,-1]
last_column

array([3, 6, 9])

In [34]:
reversed_array=arr_1[::-1]
reversed_array

array([3, 2, 1])

In [35]:
selected_element=arr_2d[arr_2d>5]
selected_element

array([6, 7, 8, 9])

Q.N.4

In [36]:
scalar=arr_2d+10
scalar

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [37]:
arr_1d=np.array([1,2,3])
mul=arr_2d*arr_1d
mul

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [38]:
dot_product=np.dot(arr_1,arr_2)
dot_product

32

In [40]:
matrix1=np.array([[1,2],[3,4]])
matrix1

array([[1, 2],
       [3, 4]])

In [41]:
matrix2=np.array([[5,6],[7,8]])
matrix2

array([[5, 6],
       [7, 8]])

In [42]:
matrix_mul=np.dot(matrix1,matrix2)

In [43]:
matrix_mul

array([[19, 22],
       [43, 50]])

In [44]:
sqrt_matrix=np.array([[1,2],[3,4]])
sqrt_matrix

array([[1, 2],
       [3, 4]])

In [50]:
inverse=np.linalg.inv(sqrt_matrix)
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [51]:
determinant=np.linalg.det(sqrt_matrix)
determinant

-2.0000000000000004