Q.N.1

Scalar is a single value(0-dimensional array)
vector is a (1-dimensional array)containing a sequence of values.
matrix is a (2-dimensinal array) containing rows and columns 

Q.N.2
We can create an arry with evenly spaced values within a range
using np.arange(start,stop,step) OR
np.linspace(start,stop,num)

In [4]:
import numpy as np
n=np.arange(0,10,2)
n

array([0, 2, 4, 6, 8])

In [5]:
linspace=np.linspace(0,1,5)
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Q.N.3


Array Broadcasting allows Numpy to perform arithematic operations on arrays of different shapes by automatically expanding smaller arrays to match the shape of larger arrays

In [6]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
b=np.array([[1],[2],[3]])
b

array([[1],
       [2],
       [3]])

In [9]:
res=a+b
res

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

Q.N.4
using arithemati operations such as (+,-,*,/) directly on arrays we can perform element-wose operations on numpyarrays

In [13]:
a1=np.array([1,2,3])
a2=np.array([5,6,7])
a1


array([1, 2, 3])

In [14]:
a2

array([5, 6, 7])

In [15]:
add=a1+a2
add

array([ 6,  8, 10])

In [17]:
sub=a1-a2
sub

array([-4, -4, -4])

Q.N.5

the purpose of np.newaxis is to add a new dimension to an array

In [18]:
aa=np.array([1,2,3])
aa

array([1, 2, 3])

In [19]:
a_2d=a[:,np.newaxis]
a_2d

array([[1],
       [2],
       [3]])

Q.N.6 
we can sort a Numpy array along a specific axis by using 
np.sort(array,axis)

In [20]:
a11=np.array([[3,1],[4,2]])
a11

array([[3, 1],
       [4, 2]])

In [24]:
sort=np.sort(a11,axis=0)
sort

array([[3, 1],
       [4, 2]])

Q.N.7

difference between np.array and np.asarray function

np.array always creates a new array
np.asarray is used when we want to convert the input to an array. 
Input can be lists, lists of tuples, tuples, tuples of tuples, tuples of lists and arrays.

In [25]:
ar=np.array([1,2,3])
ar

array([1, 2, 3])

In [26]:
list=[1,2,3]
list

[1, 2, 3]

In [27]:
c=np.asarray(list)
c

array([1, 2, 3])

Q.N.8
advantages of using Numpy over python's built-in lists for numeric operations
--> Faster computations due to optimized C implementations
--> Supports multi-dimensional arrays
--> Memory-efficient
--> provides numerious built in mathematical operations

Q.N.9
using np.save to save and 
np.load to load arrays
we can save and load Numpy arrays to from disk

In [40]:
z=np.array([1,2,3])
z


array([1, 2, 3])

In [41]:
np.save('array.npy',z)

In [42]:
load=np.load("array.npy")


In [43]:
load

array([1, 2, 3])

Q.N.10

np.where is used to return indices or values based on a condition

In [47]:
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [48]:
res=np.where(array>2)
res

(array([2, 3], dtype=int64),)